import json
import sys
from types import SimpleNamespace
from pathlib import Path

import pytest

from probes.phase2.feetech_wire import (
    BROADCAST_ID,
    GOAL_POSITION,
    INST_READ,
    PRESENT_POSITION,
    SO101_MOTOR_IDS,
    SO101_MOTOR_NAMES,
    ChecksumError,
    FeetechProtocolError,
    decode_packet,
    decode_status_packet,
    decode_sync_write,
    encode_packet,
    encode_status_packet,
    encode_sync_read,
    encode_sync_write,
    INST_WRITE,
)
from probes.phase2 import real_lerobot
from probes.phase2.real_lerobot import (
    RealProbeIdentityError,
    RealProbeUnavailable,
    SO101_PROBE_ACTION,
    _cleanup_real_follower,
    build_so101_calibration,
    run_real_so101_probe,
    so101_action_to_raw_ticks,
)
from probes.phase2.virtual_feetech import VirtualFeetechDevice, VirtualFeetechPTY


PHASE2 = Path(__file__).parents[1] / "probes" / "phase2"


def test_probe_manifest_is_source_evidence_only_and_pinned():
    manifest = json.loads((PHASE2 / "probe_manifest.json").read_text(encoding="utf-8"))
    assert manifest["probe_status"] == "PROPOSED_SOURCE_EVIDENCE"
    assert manifest["admission_status"] == "NOT_ADMITTED"
    assert manifest["authority_class"] == "SOURCE_EVIDENCE_ONLY"
    assert manifest["formal_schema"] is None
    assert manifest["formal_reference"] is None
    commits = {
        source["source_commit"]
        for source in manifest["sources"]
        if source["source_commit"] is not None
    }
    assert commits == {
        "30da8e687a6dfc617fcd94afc367ac7071c376ce",
        "7629d2ad9853d10fb903093a33ef6114099d97e5",
        "65691c8a8bc53b98d3976dba4dbf9d5d20b2e7f5",
        "ae6a8403e272733e9996ef59990880330496177f",
    }
    assert {source["license"] for source in manifest["sources"]} == {
        "Apache-2.0",
        "BSD-3-Clause",
        "Unlicense",
    }
    lerobot = next(source for source in manifest["sources"] if source["name"] == "LeRobot")
    assert lerobot["distribution"] == {
        "kind": "wheel",
        "sha256": "b38a564fbc441d98380576863bf68635dde5fc2c42ddc2a39d0486640dc9e9a8",
    }
    sdk = next(source for source in manifest["sources"] if source["name"] == "feetech-servo-sdk")
    assert sdk["version"] == "1.0.0"
    assert sdk["license"] == "Unlicense"
    assert sdk["source_url"] == "https://pypi.org/project/feetech-servo-sdk/1.0.0/"
    assert sdk["distribution"] == {
        "kind": "sdist",
        "sha256": "d4d3832e4b1b22a8222133a414db9f868224c2fb639426a1b11d96ddfe84e69c",
    }
    assert sdk["provenance"] == "THIRD_PARTY_DISTRIBUTION_NOT_HF_OR_FEETECH_OFFICIAL"


def test_packet_checksum_round_trip():
    frame = encode_packet(1, INST_READ, (PRESENT_POSITION[0], PRESENT_POSITION[1]))
    assert frame[:2] == b"\xff\xff"
    packet = decode_packet(frame)
    assert packet.motor_id == 1
    assert packet.instruction == INST_READ
    assert packet.params == bytes(PRESENT_POSITION)


def test_bad_packet_checksum_is_rejected():
    frame = bytearray(encode_packet(1, INST_READ, bytes(PRESENT_POSITION)))
    frame[-1] ^= 0x01
    with pytest.raises(ChecksumError):
        decode_packet(frame)


def test_status_packet_matches_independent_protocol0_raw_golden_bytes():
    # These literals are the wire contract, not output generated by the
    # encoder under test: FF FF ID LENGTH ERROR PARAMS CHECKSUM.
    no_error = bytes.fromhex("ff ff 01 02 00 fc")
    present_position = bytes.fromhex("ff ff 01 04 00 00 08 f2")
    assert decode_status_packet(no_error).params == b""
    decoded = decode_status_packet(present_position)
    assert decoded.motor_id == 1
    assert decoded.error == 0
    assert decoded.params == bytes.fromhex("00 08")
    bad_status = bytearray(present_position)
    bad_status[-1] ^= 0x01
    with pytest.raises(ChecksumError):
        decode_status_packet(bad_status)
    assert encode_status_packet(1) == no_error
    assert encode_status_packet(1, params=bytes.fromhex("00 08")) == present_position


def test_sync_write_goal_position_decodes_all_six_motor_values():
    values = {motor_id: bytes((motor_id, 0x10 + motor_id)) for motor_id in range(1, 7)}
    frame = encode_sync_write(GOAL_POSITION[0], GOAL_POSITION[1], values)
    sync_write = decode_sync_write(frame)
    assert sync_write.address == GOAL_POSITION[0]
    assert sync_write.data_length == GOAL_POSITION[1]
    assert sync_write.values == values
    assert decode_packet(frame).motor_id == BROADCAST_ID


def test_sync_read_present_position_returns_six_status_packets():
    positions = {motor_id: 1000 + motor_id for motor_id in range(1, 7)}
    device = VirtualFeetechDevice(present_positions=positions)
    request = encode_sync_read(PRESENT_POSITION[0], PRESENT_POSITION[1], range(1, 7))
    responses = device.handle_frame(request)
    observed = {
        status.motor_id: int.from_bytes(status.params, "little")
        for status in (decode_status_packet(response) for response in responses)
    }
    assert observed == positions


def test_virtual_device_allows_explicit_configure_protection_registers():
    device = VirtualFeetechDevice()
    for address, width in ((16, 2), (28, 2), (36, 1)):
        response = device.handle_frame(encode_packet(1, INST_WRITE, bytes((address,)) + bytes(width)))
        assert decode_status_packet(response[0]).error == 0


@pytest.mark.parametrize(
    "instruction, params",
    [
        (INST_READ, bytes((99, 1))),  # unknown address
        (INST_READ, bytes((GOAL_POSITION[0], 1))),  # known address, wrong width
        (INST_WRITE, bytes((99, 0))),  # unknown address
        (INST_WRITE, bytes((GOAL_POSITION[0], 0))),  # known address, wrong width
    ],
)
def test_virtual_device_rejects_unknown_or_wrong_width_register_access(instruction, params):
    device = VirtualFeetechDevice()
    with pytest.raises(FeetechProtocolError):
        device.handle_frame(encode_packet(1, instruction, params))


def test_so101_mapping_is_six_named_motors_with_ids_one_through_six():
    assert SO101_MOTOR_NAMES == (
        "shoulder_pan",
        "shoulder_lift",
        "elbow_flex",
        "wrist_flex",
        "wrist_roll",
        "gripper",
    )
    assert SO101_MOTOR_IDS == {name: index for index, name in enumerate(SO101_MOTOR_NAMES, 1)}


def test_real_probe_calibration_json_shape_is_explicit_for_all_six_motors():
    calibration = build_so101_calibration()
    assert set(calibration) == set(SO101_MOTOR_NAMES)
    assert calibration == {
        name: {
            "id": index,
            "drive_mode": 0,
            "homing_offset": 0,
            "range_min": 0,
            "range_max": 4095,
        }
        for index, name in enumerate(SO101_MOTOR_NAMES, 1)
    }


def test_real_probe_action_maps_to_distinct_expected_raw_ticks():
    assert len(set(SO101_PROBE_ACTION.values())) == 6
    assert so101_action_to_raw_ticks(SO101_PROBE_ACTION) == {
        1: 1706,
        2: 1933,
        3: 2161,
        4: 2388,
        5: 2616,
        6: 1023,
    }


def test_real_probe_rejects_arbitrary_serial_string():
    with pytest.raises(TypeError):
        run_real_so101_probe("/dev/ttyUSB0")


def test_real_probe_rejects_unopened_project_pty():
    virtual_port = VirtualFeetechPTY()
    assert not virtual_port.is_open
    with pytest.raises(ValueError):
        run_real_so101_probe(virtual_port)


def test_project_owned_pty_is_open_only_inside_context():
    virtual_port = VirtualFeetechPTY()
    with virtual_port:
        assert virtual_port.is_open
        assert virtual_port.port
    assert not virtual_port.is_open


class _CleanupFakeFollower:
    def __init__(self, follower_connected, bus_connected, cleanup_error=None):
        self.is_connected = follower_connected
        self.bus = SimpleNamespace(is_connected=bus_connected)
        self.cleanup_error = cleanup_error
        self.disconnect_calls = 0

    def disconnect(self):
        self.disconnect_calls += 1
        if self.cleanup_error is not None:
            raise self.cleanup_error
        self.is_connected = False
        self.bus.is_connected = False


def test_cleanup_uses_bus_state_when_connect_failed_before_connected_flag():
    follower = _CleanupFakeFollower(follower_connected=False, bus_connected=True)
    _cleanup_real_follower(follower, RuntimeError("primary connect failure"))
    assert follower.disconnect_calls == 1


def test_cleanup_failure_preserves_primary_and_exposes_without_primary():
    primary = ValueError("primary failure")
    with pytest.raises(ValueError, match="primary failure"):
        follower = _CleanupFakeFollower(
            follower_connected=False,
            bus_connected=True,
            cleanup_error=RuntimeError("cleanup failure"),
        )
        try:
            raise primary
        except BaseException as primary_error:
            _cleanup_real_follower(follower, primary_error)
            raise

    follower = _CleanupFakeFollower(
        follower_connected=False,
        bus_connected=True,
        cleanup_error=RuntimeError("cleanup failure"),
    )
    with pytest.raises(RuntimeError, match="cleanup failure"):
        _cleanup_real_follower(follower, None)


def test_real_probe_accepts_exact_distribution_versions_without_importing_optional_stack(monkeypatch):
    versions = {"lerobot": "0.6.0", "feetech-servo-sdk": "1.0.0"}
    monkeypatch.setattr(real_lerobot.metadata, "version", versions.__getitem__)
    assert real_lerobot.verify_pinned_distribution_identity() == versions


def test_real_probe_missing_distribution_is_unavailable(monkeypatch):
    def missing(distribution):
        raise real_lerobot.metadata.PackageNotFoundError(distribution)

    monkeypatch.setattr(real_lerobot.metadata, "version", missing)
    with pytest.raises(RealProbeUnavailable):
        real_lerobot._load_real_symbols()


def test_real_probe_wrong_distribution_version_is_identity_error_not_skip(monkeypatch):
    versions = {"lerobot": "0.5.3", "feetech-servo-sdk": "1.0.0"}
    monkeypatch.setattr(real_lerobot.metadata, "version", versions.__getitem__)
    with pytest.raises(RealProbeIdentityError, match="lerobot==0.6.0"):
        real_lerobot._load_real_symbols()


@pytest.mark.skipif(
    sys.platform != "linux",
    reason="real LeRobot/scservo_sdk PTY integration is Linux-only; current platform is not Linux",
)
def test_real_pinned_lerobot_so101_uses_real_bus_over_pty():
    try:
        with VirtualFeetechPTY() as virtual_port:
            result = run_real_so101_probe(virtual_port)
            expected_raw = so101_action_to_raw_ticks(SO101_PROBE_ACTION)
            assert result.sent_action == SO101_PROBE_ACTION
            assert virtual_port.device.goal_positions == expected_raw
            observed_raw = so101_action_to_raw_ticks(result.observation)
            assert all(
                abs(observed_raw[motor_id] - expected_tick) <= 1
                for motor_id, expected_tick in expected_raw.items()
            )
    except RealProbeUnavailable as exc:
        pytest.skip(str(exc))
