import json
import sys
from pathlib import Path

import pytest

from probes.phase2.feetech_wire import (
    BROADCAST_ID,
    GOAL_POSITION,
    INST_READ,
    PRESENT_POSITION,
    SO101_MOTOR_IDS,
    SO101_MOTOR_NAMES,
    ChecksumError,
    decode_packet,
    decode_status_packet,
    decode_sync_write,
    encode_packet,
    encode_status_packet,
    encode_sync_read,
    encode_sync_write,
)
from probes.phase2.real_lerobot import RealProbeUnavailable, run_real_so101_probe
from probes.phase2.virtual_feetech import VirtualFeetechDevice, VirtualFeetechPTY


PHASE2 = Path(__file__).parents[1] / "probes" / "phase2"


def test_probe_manifest_is_source_evidence_only_and_pinned():
    manifest = json.loads((PHASE2 / "probe_manifest.json").read_text(encoding="utf-8"))
    assert manifest["probe_status"] == "PROPOSED_SOURCE_EVIDENCE"
    assert manifest["admission_status"] == "NOT_ADMITTED"
    assert manifest["authority_class"] == "SOURCE_EVIDENCE_ONLY"
    assert manifest["formal_schema"] is None
    assert manifest["formal_reference"] is None
    commits = {
        source["source_commit"]
        for source in manifest["sources"]
        if source["source_commit"] is not None
    }
    assert commits == {
        "30da8e687a6dfc617fcd94afc367ac7071c376ce",
        "7629d2ad9853d10fb903093a33ef6114099d97e5",
        "65691c8a8bc53b98d3976dba4dbf9d5d20b2e7f5",
        "ae6a8403e272733e9996ef59990880330496177f",
    }
    assert {source["license"] for source in manifest["sources"]} == {
        "Apache-2.0",
        "BSD-3-Clause",
        "Unlicense",
    }
    lerobot = next(source for source in manifest["sources"] if source["name"] == "LeRobot")
    assert lerobot["distribution"] == {
        "kind": "wheel",
        "sha256": "b38a564fbc441d98380576863bf68635dde5fc2c42ddc2a39d0486640dc9e9a8",
    }
    sdk = next(source for source in manifest["sources"] if source["name"] == "feetech-servo-sdk")
    assert sdk["version"] == "1.0.0"
    assert sdk["license"] == "Unlicense"
    assert sdk["source_url"] == "https://pypi.org/project/feetech-servo-sdk/1.0.0/"
    assert sdk["distribution"] == {
        "kind": "sdist",
        "sha256": "d4d3832e4b1b22a8222133a414db9f868224c2fb639426a1b11d96ddfe84e69c",
    }
    assert sdk["provenance"] == "THIRD_PARTY_DISTRIBUTION_NOT_HF_OR_FEETECH_OFFICIAL"


def test_packet_checksum_round_trip():
    frame = encode_packet(1, INST_READ, (PRESENT_POSITION[0], PRESENT_POSITION[1]))
    assert frame[:2] == b"\xff\xff"
    packet = decode_packet(frame)
    assert packet.motor_id == 1
    assert packet.instruction == INST_READ
    assert packet.params == bytes(PRESENT_POSITION)


def test_bad_packet_checksum_is_rejected():
    frame = bytearray(encode_packet(1, INST_READ, bytes(PRESENT_POSITION)))
    frame[-1] ^= 0x01
    with pytest.raises(ChecksumError):
        decode_packet(frame)


def test_status_packet_matches_independent_protocol0_raw_golden_bytes():
    # These literals are the wire contract, not output generated by the
    # encoder under test: FF FF ID LENGTH ERROR PARAMS CHECKSUM.
    no_error = bytes.fromhex("ff ff 01 02 00 fc")
    present_position = bytes.fromhex("ff ff 01 04 00 00 08 f2")
    assert decode_status_packet(no_error).params == b""
    decoded = decode_status_packet(present_position)
    assert decoded.motor_id == 1
    assert decoded.error == 0
    assert decoded.params == bytes.fromhex("00 08")
    bad_status = bytearray(present_position)
    bad_status[-1] ^= 0x01
    with pytest.raises(ChecksumError):
        decode_status_packet(bad_status)
    assert encode_status_packet(1) == no_error
    assert encode_status_packet(1, params=bytes.fromhex("00 08")) == present_position


def test_sync_write_goal_position_decodes_all_six_motor_values():
    values = {motor_id: bytes((motor_id, 0x10 + motor_id)) for motor_id in range(1, 7)}
    frame = encode_sync_write(GOAL_POSITION[0], GOAL_POSITION[1], values)
    sync_write = decode_sync_write(frame)
    assert sync_write.address == GOAL_POSITION[0]
    assert sync_write.data_length == GOAL_POSITION[1]
    assert sync_write.values == values
    assert decode_packet(frame).motor_id == BROADCAST_ID


def test_sync_read_present_position_returns_six_status_packets():
    positions = {motor_id: 1000 + motor_id for motor_id in range(1, 7)}
    device = VirtualFeetechDevice(present_positions=positions)
    request = encode_sync_read(PRESENT_POSITION[0], PRESENT_POSITION[1], range(1, 7))
    responses = device.handle_frame(request)
    observed = {
        status.motor_id: int.from_bytes(status.params, "little")
        for status in (decode_status_packet(response) for response in responses)
    }
    assert observed == positions


def test_so101_mapping_is_six_named_motors_with_ids_one_through_six():
    assert SO101_MOTOR_NAMES == (
        "shoulder_pan",
        "shoulder_lift",
        "elbow_flex",
        "wrist_flex",
        "wrist_roll",
        "gripper",
    )
    assert SO101_MOTOR_IDS == {name: index for index, name in enumerate(SO101_MOTOR_NAMES, 1)}


@pytest.mark.skipif(
    sys.platform != "linux",
    reason="real LeRobot/scservo_sdk PTY integration is Linux-only; current platform is not Linux",
)
def test_real_pinned_lerobot_so101_uses_real_bus_over_pty():
    try:
        with VirtualFeetechPTY() as virtual_port:
            result = run_real_so101_probe(virtual_port.port)
    except RealProbeUnavailable as exc:
        pytest.skip(str(exc))
    assert set(result.sent_action) == {f"{name}.pos" for name in SO101_MOTOR_NAMES}
    assert set(result.observation) == {f"{name}.pos" for name in SO101_MOTOR_NAMES}
